name: Analyze

on:
  pull_request:
  push:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  job:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Init CodeQL
      uses: github/codeql-action/init@v1

    - name: Analyze
      uses: github/codeql-action/analyze@v1
