name: Release

on:
  release:
    types: [created]

jobs:
  job:
    name: Upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools twine wheel

    - name: Build
      run: python setup.py sdist bdist_wheel

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*
